1  # docker-compose.yaml
2  version: '3.6'
3  services:
4    jenkins:
5      image: jenkins/jenkins:lts
6      privileged: true
7      user: root
8      ports:
9       - 8080:8080
10      - 70000:70000
11    container_name: jenkins
12    volumes:
13      - /home/${test}/jenkins_compose/jenkins_configuration:/var/jenkins_home
14      - /var/run/docker.sock:/var/run/docker.sock